[tool.poetry]
name = "poetry-instance"
version = "1.6.1"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "3.8.10"
poetry = "^1.6.1"

[tool.poetry.group.additional.dependencies]
poetry-plugin-up = "^0.3.0"

