#!/usr/bin/env bash

set -o errexit  # exit on fail
set -o pipefail # catch errors in pipelines
set -o nounset  # exit on undeclared variable
# set -o xtrace    # trace execution


DATA_DIR=${XDG_DATA_HOME:-${HOME}/.local/share}/surviv
mkdir -p "${DATA_DIR}/${1}"


for (( offset=0; 1; offset+=50 )); do
    DATA="{\"slug\":\"${1}\",\"offset\":${offset},\"count\":50,\"teamModeFilter\":7}"
    echo "Fetching for ${1} with offset ${offset}"

    if command -v curl >/dev/null; then
        JSON="$(
            curl 'https://surviv.io/api/match_history' \
                --silent \
                --header 'content-type: application/json' \
                --data-binary "${DATA}"
        )"
    fi

    GUIDS="$(jq --raw-output '.[] | .guid' <<<"${JSON}")"

    EXISTING=
    for guid in ${GUIDS}; do
        if [[ -f ${DATA_DIR}/${1}/${guid}.json ]]; then
            EXISTING=1
        else
            echo "Saving ${guid}"
            jq --raw-output ".[] | select(.guid==\"${guid}\")" <<<"${JSON}" > "${DATA_DIR}/${1}/${guid}.json"
        fi
    done

    if [[ ${EXISTING} == 1 || -z ${GUIDS} ]]; then
        break
    fi
done





    # wget -O- --post-data='{"some data to post..."}' \
    #   --header='Content-Type:application/json' \
    #   'http://www.example.com:9000/json'