#!/bin/sh

set -o errexit  # exit on fail
set -o nounset  # exit on undeclared variable
# set -o xtrace   # trace execution


save_path="${HOME}/0files/imgs/screenshots/$(date '+%s_%Y.%m.%d_%H:%M:%S').png"


if command -v maim xdotool >/dev/null; then
    [ "${1}" = 'full'    ] && maim                                         -- "${save_path}"
    [ "${1}" = 'select'  ] && maim --select                                -- "${save_path}"
    [ "${1}" = 'focused' ] && maim --window "$(xdotool getwindowfocus -f)" -- "${save_path}"

elif command -v scrot >/dev/null; then
    [ "${1}" = 'full'    ] && scrot --multidisp -- "${save_path}"
    [ "${1}" = 'select'  ] && scrot --select    -- "${save_path}"
    [ "${1}" = 'focused' ] && scrot --focused   -- "${save_path}"

elif command -v xdotool gm >/dev/null; then
    [ "${1}" = 'full'    ] && gm import -window root                           "${save_path}"
    [ "${1}" = 'select'  ] && gm import                                        "${save_path}"
    [ "${1}" = 'focused' ] && gm import -window "$(xdotool getwindowfocus -f)" "${save_path}"

elif command -v xdotool import >/dev/null; then
    [ "${1}" = 'full'    ] && import -window root                           -- "${save_path}"
    [ "${1}" = 'select'  ] && import                                        -- "${save_path}"
    [ "${1}" = 'focused' ] && import -window "$(xdotool getwindowfocus -f)" -- "${save_path}"

else
    # current xwd lacks -rect option on ubuntu: can't test
    # escrotum not in the repos
    echo "No graphics/image-magick's import or scrot or maim installed"
    exit 1

fi


if command -v xclip >/dev/null; then
    printf '%s' "${save_path}" | xclip -in -selection primary
    xclip -selection clipboard -target image/png <"${save_path}"
fi


printf '%s' "${save_path}"
