#!/bin/sh

set -o errexit  # exit on fail
set -o nounset  # exit on undeclared variable
# set -o xtrace   # trace execution


save_dir=${HOME}/0files/imgs/screenshots
save_ext=png
save_date=$(date '+%s_%Y.%m.%d_%H:%M:%S')
save_name=${save_date}.${save_ext}
save_path=${save_dir}/${save_name}

mkdir -p "${save_dir}"


if command -v maim xdotool >/dev/null; then
    [ "${1}" = 'full'    ] && maim                                         -- "${save_path}"
    [ "${1}" = 'select'  ] && maim --select                                -- "${save_path}"
    [ "${1}" = 'focused' ] && maim --window "$(xdotool getwindowfocus -f)" -- "${save_path}"

elif command -v scrot >/dev/null; then
    [ "${1}" = 'full'    ] && scrot --multidisp -- "${save_path}"
    [ "${1}" = 'select'  ] && scrot --select    -- "${save_path}"
    [ "${1}" = 'focused' ] && scrot --focused   -- "${save_path}"

elif command -v xdotool gm >/dev/null; then
    [ "${1}" = 'full'    ] && gm import -window root                           "${save_path}"
    [ "${1}" = 'select'  ] && gm import                                        "${save_path}"
    [ "${1}" = 'focused' ] && gm import -window "$(xdotool getwindowfocus -f)" "${save_path}"

elif command -v xdotool import >/dev/null; then
    [ "${1}" = 'full'    ] && import -window root                           -- "${save_path}"
    [ "${1}" = 'select'  ] && import                                        -- "${save_path}"
    [ "${1}" = 'focused' ] && import -window "$(xdotool getwindowfocus -f)" -- "${save_path}"

else
    # current xwd lacks -rect option on ubuntu: can't test
    # escrotum not in the repos
    echo "No graphics/image-magick's import or scrot or maim installed"
    exit 1

fi


if command -v xclip >/dev/null; then
    printf '%s' "${save_path}" | xclip -in -selection primary
    xclip -selection clipboard -target image/png <"${save_path}"

elif command -v xsel >/dev/null; then
    printf '%s' "${save_path}" | xsel --input --primary
    printf '%s' "${save_path}" | xsel --input --clipboard
fi


printf '%s' "${save_path}"


(
    # Execute under lock
    # if flock is available
    if command -v flock >/dev/null; then
        flock 9
    fi

    if   [ "${save_ext}" = "png" ] && command -v optipng   >/dev/null; then
        optipng -o7 -strip all "${save_path}"
        printf "%s\n" "${save_name}" >> "${save_dir}/.optimized"

    elif [ "${save_ext}" = "png" ] && command -v optipng   >/dev/null; then
        pngcrush -brute -reduce "${save_path}" "/tmp/${save_name}"
        mv "/tmp/${save_name}" "${save_path}"
        printf "%s\n" "${save_name}" >> "${save_dir}/.optimized"

    elif [ "${save_ext}" = "jpg" ] && command -v jpegoptim >/dev/null; then
        jpegoptim --strip-all "${save_path}"
        printf "%s\n" "${save_name}" >> "${save_dir}/.optimized"

    fi

    if command -v tesseract >/dev/null; then
        tesseract -l eng+rus --psm 1 "${save_path}" "${save_dir}/${save_date}"
    fi

) 9>"/var/lock/screenshot-$(id -u).lock"
