#!/usr/bin/env bash

set -o errexit  # exit on fail
set -o pipefail # catch errors in pipelines
set -o nounset  # exit on undeclared variable
# set -o xtrace    # trace execution


pretty_uptime=$(ssh synology uptime |cut -d ' ' -f5 |cut -d ',' -f1)

uptime_seconds=$((
    $(date --date="$(date +'%Y-%m-%d') ${pretty_uptime}" +%s) -
    $(date --date="$(date +'%Y-%m-%d')                 " +%s)
))


start_epoch=$(( $(date +%s) - uptime_seconds ))

real_start_time=$(date --date="@${start_epoch}" +%s)
expected_start_time=$(date --date="13:00" +%s)

delta=$(( real_start_time - expected_start_time ))
delta=${delta/-/}


if [[ ${delta} -le $(( 5 * 60 )) ]]; then
    echo Powering off...
    ssh synology poweroff
    echo Powered off

else
    echo Not powering off

fi
