#!/usr/bin/env bash

set -o errexit  # exit on fail
set -o pipefail # catch errors in pipelines
set -o nounset  # exit on undeclared variable
# set -o xtrace    # trace execution


uptime_seconds=$(ssh synology cat /proc/uptime |cut --fields=1 --delimiter=.)
boot_epoch=$(date -d "${uptime_seconds} seconds ago" +%s)
expected_boot_epoch=$(date --date="13:00" +%s)

delta=$(( boot_epoch - expected_boot_epoch ))
delta=${delta/-/}


if [[ ${delta} -le $(( 5 * 60 )) ]]; then
    echo Powering off...
    ssh synology poweroff
    echo Powered off

else
    echo Not powering off

fi
