#!/bin/sh

set -o errexit  # exit on fail
set -o nounset  # exit on undeclared variable
# set -o xtrace   # trace execution


# Current script's directory
# we do not resolve links through `pwd -P`
# so that
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)


# Drop current path from PATH variable
PATH=$(
    printf "%s" "${PATH}" |
    tr : '\n' |
    while read -r path; do
        [ "${path}" != "${DIR}" ] && printf "%s:" "${path}"
    done
)
PATH=${PATH%?}  # Drop ending ':'

# Now we can get where the original zathura is
ORIG_EXECUTABLE=$(command -v zathura)

# exec bwrap --dev-bind / / \
exec "${ORIG_EXECUTABLE}" "$@"

# env -i bwrap      \
#     --setenv DISPLAY         ":0"                  \
#     --setenv XDG_RUNTIME_DIR "/run/user/$(id -u)"  \
#     --setenv XAUTHORITY      "${HOME}/.Xauthority" \
#     --setenv HOME            "${HOME}"             \
#     --proc    /proc                                         \
#     --bind    /tmp/.X11-unix/X0       /tmp/.X11-unix/X0     \
#     --ro-bind "${ORIG_EXECUTABLE}"    "${ORIG_EXECUTABLE}"  \
#     --ro-bind "${HOME}"               "${HOME}"             \
#     --ro-bind /etc                    /etc                  \
#     --ro-bind /lib/locale             /lib/locale           \
#     --ro-bind /lib/x86_64-linux-gnu   /lib/x86_64-linux-gnu \
#     --ro-bind /lib64                  /lib64                \
#     --ro-bind /run                    /run                  \
#     --ro-bind /usr                    /usr                  \
#     --ro-bind /usr/local/share        /usr/local/share      \
#     --ro-bind /usr/share              /usr/share            \
#     --unshare-all \
#     "${ORIG_EXECUTABLE}" "$@"
